In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor

In [2]:
columns = [
    'timestamp',
    'city',
    'current_temp',
    'feels_like',
    'humidity',
    'wind_speed',
    'weather_description',
    'temp_min',
    'temp_max',
    'pressure',
    'country',
    'visibility'
]

df = pd.read_csv(
    "/home/Aqib/Desktop/weather_forecast/weather_data.csv",
    header=None,
    names=columns
)

df.head()

,timestamp,city,current_temp,feels_like,humidity,wind_speed,weather_description,temp_min,temp_max,pressure,country,visibility
0,2026-05-07 16:59:05,Mumbai,33,40,62,6.69,haze,32,33,1005,IN,4500
1,2026-05-07 16:59:05,Delhi,30,29,37,7.72,clear sky,30,30,1006,IN,6000
2,2026-05-07 16:59:05,Bengaluru,32,33,43,7.15,scattered clouds,31,33,1004,IN,8000
3,2026-05-07 16:59:05,Hyderabad,35,36,34,3.60,scattered clouds,35,36,1004,IN,6000
4,2026-05-07 16:59:06,Ahmedabad,40,38,15,3.60,smoke,40,40,1003,IN,5000

In [3]:
df['timestamp'] = pd.to_datetime(df['timestamp'])

df['hour'] = df['timestamp'].dt.hour

df['day'] = df['timestamp'].dt.day

df['month'] = df['timestamp'].dt.month

df['day_of_week'] = df['timestamp'].dt.dayofweek

df.sample(5)

,timestamp,city,current_temp,feels_like,humidity,wind_speed,weather_description,temp_min,temp_max,pressure,country,visibility,hour,day,month,day_of_week
46,2026-05-07 16:59:18,Chandigarh,30,29,39,5.66,broken clouds,30,30,1006,IN,6000,16,7,5,3
1253,2026-05-09 18:00:02,Kolkata,26,26,69,5.14,thunderstorm,26,26,1005,IN,3500,18,9,5,5
1259,2026-05-09 18:00:04,Nagpur,34,32,24,7.72,thunderstorm,34,34,1002,IN,5000,18,9,5,5
1194,2026-05-09 15:00:15,Chandigarh,34,34,36,1.54,scattered clouds,34,34,1006,IN,6000,15,9,5,5
1085,2026-05-09 11:00:15,Coimbatore,30,33,62,2.06,haze,30,30,1011,IN,6000,11,9,5,5

In [4]:
df['target_temp_next_hour'] = (
    df.groupby('city')['current_temp']
      .shift(-1)
)
df.head(-5)

,timestamp,city,current_temp,feels_like,humidity,wind_speed,weather_description,temp_min,temp_max,pressure,country,visibility,hour,day,month,day_of_week,target_temp_next_hour
0,2026-05-07 16:59:05,Mumbai,33,40,62,6.69,haze,32,33,1005,IN,4500,16,7,5,3,33.0
1,2026-05-07 16:59:05,Delhi,30,29,37,7.72,clear sky,30,30,1006,IN,6000,16,7,5,3,29.0
2,2026-05-07 16:59:05,Bengaluru,32,33,43,7.15,scattered clouds,31,33,1004,IN,8000,16,7,5,3,31.0
3,2026-05-07 16:59:05,Hyderabad,35,36,34,3.60,scattered clouds,35,36,1004,IN,6000,16,7,5,3,34.0
4,2026-05-07 16:59:06,Ahmedabad,40,38,15,3.60,smoke,40,40,1003,IN,5000,16,7,5,3,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1387,2026-05-09 22:00:14,Gwalior,31,34,58,4.12,clear sky,31,31,1005,IN,6000,22,9,5,5,NaN
1388,2026-05-09 22:00:14,Vijayawada,29,33,70,3.09,scattered clouds,29,29,1008,IN,6000,22,9,5,5,NaN
1389,2026-05-09 22:00:15,Jodhpur,38,35,14,4.12,overcast clouds,38,38,1005,IN,10000,22,9,5,5,NaN
1390,2026-05-09 22:00:15,Madurai,28,33,83,1.54,mist,28,28,1010,IN,5000,22,9,5,5,NaN
1391,2026-05-09 22:00:15,Raipur,27,27,44,3.60,haze,27,27,1009,IN,3000,22,9,5,5,NaN

In [5]:
df['temp_lag_1'] = (
    df.groupby('city')['current_temp']
      .shift(1)
)

df['temp_lag_2'] = (
    df.groupby('city')['current_temp']
      .shift(2)
)

df['temp_lag_3'] = (
    df.groupby('city')['current_temp']
      .shift(3)
)

df.sample(5)

,timestamp,city,current_temp,feels_like,humidity,wind_speed,weather_description,temp_min,temp_max,pressure,country,visibility,hour,day,month,day_of_week,target_temp_next_hour,temp_lag_1,temp_lag_2,temp_lag_3
312,2026-05-07 23:00:06,Bhopal,27,27,34,3.60,few clouds,27,27,1007,IN,6000,23,7,5,3,33.0,33.0,35.0,36.0
765,2026-05-08 19:20:07,Patna,24,24,73,7.20,haze,24,24,1007,IN,4000,19,8,5,4,23.0,24.0,24.0,18.0
1341,2026-05-09 20:00:23,Raipur,24,24,64,8.23,thunderstorm,24,24,1007,IN,3000,20,9,5,5,27.0,29.0,25.0,36.0
174,2026-05-07 18:24:09,Kalyan-Dombivli,35,36,37,3.74,overcast clouds,35,35,1006,IN,10000,18,7,5,3,35.0,35.0,35.0,37.0
1383,2026-05-09 22:00:13,Ranchi,19,19,77,8.23,overcast clouds,19,19,1010,IN,1300,22,9,5,5,NaN,20.0,21.0,22.0

In [6]:
df['rolling_temp_mean_3'] = (
    df.groupby('city')['current_temp']
      .transform(lambda x: x.rolling(3).mean())
)

In [7]:
categorical_cols = ['city', 'weather_description', 'country']

le = LabelEncoder()

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.sample(5)

,timestamp,city,current_temp,feels_like,humidity,wind_speed,weather_description,temp_min,temp_max,pressure,...,visibility,hour,day,month,day_of_week,target_temp_next_hour,temp_lag_1,temp_lag_2,temp_lag_3,rolling_temp_mean_3
372,2026-05-08 00:00:08,30,27,27,41,4.46,1,27,27,1007,...,10000,0,8,5,4,31.0,28.0,31.0,32.0,28.666667
105,2026-05-07 18:22:03,43,33,40,62,4.12,3,33,33,1004,...,6000,18,7,5,3,33.0,33.0,38.0,NaN,34.666667
1228,2026-05-09 17:00:12,4,32,32,40,1.54,0,32,32,1003,...,6000,17,9,5,5,34.0,39.0,37.0,34.0,36.000000
516,2026-05-08 13:00:08,45,39,37,18,3.09,1,39,39,1006,...,6000,13,8,5,4,41.0,39.0,33.0,33.0,37.000000
66,2026-05-07 18:20:06,36,32,32,35,6.42,1,32,32,1006,...,10000,18,7,5,3,32.0,37.0,NaN,NaN,NaN

In [8]:
df.dropna(inplace=True)
df.sample(5)

,timestamp,city,current_temp,feels_like,humidity,wind_speed,weather_description,temp_min,temp_max,pressure,...,visibility,hour,day,month,day_of_week,target_temp_next_hour,temp_lag_1,temp_lag_2,temp_lag_3,rolling_temp_mean_3
210,2026-05-07 19:00:05,19,36,34,21,3.09,3,36,36,1005,...,6000,19,7,5,3,34.0,37.0,37.0,37.0,36.666667
883,2026-05-08 23:00:12,40,21,21,83,2.57,7,21,21,1009,...,3500,23,8,5,4,21.0,21.0,22.0,22.0,21.333333
700,2026-05-08 19:18:04,18,33,34,40,5.14,10,33,33,1009,...,6000,19,8,5,4,33.0,33.0,35.0,35.0,33.666667
395,2026-05-08 00:00:14,41,33,32,32,5.71,9,33,33,1008,...,10000,0,8,5,4,35.0,33.0,31.0,31.0,32.333333
950,2026-05-09 09:00:03,18,28,30,61,4.12,3,28,30,1014,...,6000,9,9,5,5,30.0,28.0,29.0,32.0,28.333333

In [9]:
x = df.drop(
    ['target_temp_next_hour', 'timestamp'],
    axis=1
)

y = df['target_temp_next_hour']

rf = RandomForestRegressor(n_estimators=100, random_state=42,)
rf.fit(x,y)

importance = rf.feature_importances_

In [10]:
feature_important_df= pd.DataFrame({
    'feature':x.columns,
    'Importance': importance
})

feature_important_df = feature_important_df.sort_values(
    by='Importance',
    ascending=False
)

feature_important_df

                feature  Importance
1          current_temp    0.331000
6              temp_min    0.266519
7              temp_max    0.100469
11                 hour    0.088908
2            feels_like    0.078442
17           temp_lag_3    0.021432
3              humidity    0.016665
0                  city    0.016636
4            wind_speed    0.016151
18  rolling_temp_mean_3    0.014197
8              pressure    0.012275
5   weather_description    0.011834
16           temp_lag_2    0.009339
15           temp_lag_1    0.006373
10           visibility    0.005396
12                  day    0.002227
14          day_of_week    0.002136
9               country    0.000000
13                month    0.000000

In [11]:
df.drop('day_of_week', axis=1, inplace=True)
df.sample(5)

,timestamp,city,current_temp,feels_like,humidity,wind_speed,weather_description,temp_min,temp_max,pressure,country,visibility,hour,day,month,target_temp_next_hour,temp_lag_1,temp_lag_2,temp_lag_3,rolling_temp_mean_3
1105,2026-05-09 14:00:07,37,38,36,16,3.51,0,38,38,1007,0,10000,14,9,5,37.0,34.0,32.0,31.0,34.666667
376,2026-05-08 00:00:09,46,26,26,61,0.00,4,26,26,1007,0,3500,0,8,5,36.0,27.0,30.0,32.0,27.666667
458,2026-05-08 12:00:06,24,31,30,27,1.76,1,31,31,1009,0,10000,12,8,5,33.0,30.0,28.0,28.0,29.666667
684,2026-05-08 19:08:40,17,30,36,74,2.57,4,30,30,1007,0,3500,19,8,5,30.0,32.0,32.0,32.0,31.333333
742,2026-05-08 19:18:36,26,39,36,11,6.21,3,39,39,1004,0,10000,19,8,5,39.0,39.0,42.0,42.0,40.000000

In [ ]:
df.to_csv(
    "/home/Aqib/Desktop/weather_forecast/live_data/engineered_weather_data.csv",
    index=False
)

In [ ]:
sample_engineered_df = df.head(100)

sample_engineered_df.to_csv(
    "/home/Aqib/Desktop/weather_forecast/live_data/engineered_weather_data.csv",
    index=False
)